name: Publish 8.4 Apache on Debian Bookworm
on:
    workflow_run: 
     workflows: ["Publish Encrypted Execution Tools"]
     types:
      - completed
    push:
      branches:
        - main
      paths:
      - '8.4/bookworm/apache/**'
      - '.github/workflows/8.4-apache-publish.yml'
jobs:
    build:
      if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}            
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: List 8.4 Apache on Debian Bookworm contents
        run: ls -trla
        shell: bash
        working-directory: ./8.4/bookworm/apache/
      - name: Build
        run: ./publish-image.sh -g
        shell: bash
        working-directory: ./8.4/bookworm/apache/
#      - name: Run Test Suite
#        run: ./workflow-test.sh
#        shell: bash
#        working-directory: ./encrypted-execution/tools/test/
#      - name: Publish 8.4 Apache Git Package Repository
#        run: ./publish-image.sh -g
#        shell: bash
#        working-directory: ./8.4/bookworm/apache/
#      - name: Trigger Downstream
#        run: |
#             curl \
#             -X POST \
#             -H 'Accept: application/vnd.github.v3+json' \
#             https://api.github.com/repos/encrypted-execution/encrypted-execution-wordpress/dispatches \
#             -d '{"event_type" : "build_8.4_apache", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
        
