name: Publish Encrypted Execution Tools
on: 
  push:
    branches:
     - main
jobs:
    build:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Encrypted Execution Tools Git Package Repository
        run: ./publish-image.sh -p
        shell: bash
        working-directory: ./encrypted-execution/
        env:
          headsha: ${{ github.sha }}
